library(tidyverse)
library(tidycensus)
library(sf)


geo <- get_acs(geography = "tract", 
          variables = "C02003_001",
          year = 2018,
          state = "IL",
          county = 31,
          geometry = TRUE) |>
  select(GEOID, geometry)


hmda_il <- read.csv("data/2018_public_lar_csv.csv")
hmda_chicago <- hmda_il |>
  filter(county_code == "17031")

hmda_chicago <-
  hmda_chicago |>
  mutate(action_taken = case_when(
    action_taken == 1 ~ "Loan originated",
    action_taken == 2 ~ "Application approved but not accepted",
    action_taken == 3 ~ "Application denied",
    action_taken == 4 ~ "Application withdrawn by applicant",
    action_taken == 5 ~ "File closed for incompleteness",
    action_taken == 6 ~ "Purchased loan",
    action_taken == 7 ~ "Preapproval request denied",
    action_taken == 8 ~ "Preapproval request approved but not accepted"),
    purchaser_type = case_when(
      purchaser_type == 0 ~ "Not applicable",
      purchaser_type == 1 ~ "Fannie Mae",
      purchaser_type == 2 ~ "Ginnie Mae",
      purchaser_type == 3 ~ "Freddie Mac",
      purchaser_type == 4 ~ "Farmer Mac",
      purchaser_type == 5 ~ "Private securitizer",
      purchaser_type == 6 ~ "Commercial bank, savings bank, or savings association",
      purchaser_type == 71 ~ "Credit union, mortgage company, or finance company",
      purchaser_type == 72 ~ "Life insurance company",
      purchaser_type == 8 ~ "Affiliate institution",
      purchaser_type == 9 ~ "Other type of purchaser"),
    preapproval = case_when(
      preapproval == 1 ~ "Preapproval requested",
      preapproval == 2 ~ "Preapproval not requested"),
    loan_type = case_when(
      loan_type == 1 ~ "Conventional (not insured or guaranteed by FHA, VA, RHS, or FSA)",
      loan_type == 2 ~ "Federal Housing Administration insured (FHA)",
      loan_type == 3 ~ "Veterans Affairs guaranteed (VA)",
      loan_type == 4 ~ "USDA Rural Housing Service or Farm Service Agency guaranteed (RHS or FSA)"),
    loan_purpose = case_when(
      loan_purpose == 1 ~ "Home purchase",
      loan_purpose == 2 ~ "Home improvement",
      loan_purpose == 31 ~ "Refinancing",
      loan_purpose == 32 ~ "Cash~out refinancing",
      loan_purpose == 4 ~ "Other purpose",
      loan_purpose == 5 ~ "Not applicable"),
    lien_status = case_when(
      lien_status == 1 ~ "Secured by a first lien",
      lien_status == 2 ~ "Secured by a subordinate lien"),
    reverse_mortgage = case_when(
      reverse_mortgage == 1 ~ "Reverse mortgage",
      reverse_mortgage == 2 ~ "Not a reverse mortgage",
      reverse_mortgage == 1111 ~ "Exempt"),
    open_end_line_of_credit = case_when(
      open_end_line_of_credit == 1 ~ "Open-end line of credit",
      open_end_line_of_credit == 2 ~ "Not an open-end line of credit",
      open_end_line_of_credit == 1111 ~ "Exempt"),
    business_or_commercial_purpose = case_when(
      business_or_commercial_purpose == 1 ~ "Primarily for a business or commercial purpose",
      business_or_commercial_purpose == 2 ~ "Not primarily for a business or commercial purpose",
      business_or_commercial_purpose == 1111 ~ "Exempt"),
    hoepa_status = case_when(
      hoepa_status == 1 ~ "High-cost mortgage",
      hoepa_status == 2 ~ "Not a high-cost mortgage",
      hoepa_status == 3 ~ "Not applicable"),
    negative_amortization = case_when(
      negative_amortization == 1 ~ "Negative amortization",
      negative_amortization == 2 ~ "No negative amortization",
      negative_amortization == 1111 ~ "Exempt"),
    interest_only_payment = case_when(
      interest_only_payment == 1 ~ "Interest-only payments",
      interest_only_payment == 2 ~ "No interest-only payments",
      interest_only_payment == 1111 ~ "Exempt"),
    balloon_payment = case_when(
      balloon_payment == 1 ~ "Balloon payment",
      balloon_payment == 2 ~ "No balloon payment",
      balloon_payment == 1111 ~ "Exempt"),
    other_nonamortizing_features = case_when(
      other_nonamortizing_features == 1 ~ "Other non-fully amortizing features",
      other_nonamortizing_features == 2 ~ "No other non-fully amortizing features",
      other_nonamortizing_features == 1111 ~ "Exempt"),
    construction_method = case_when(
      construction_method == 1 ~ "Site-built",
      construction_method == 2 ~ "Manufactured home"),
    occupancy_type = case_when(
      occupancy_type == 1 ~ "Principal residence",
      occupancy_type == 2 ~ "Second residence",
      occupancy_type == 3 ~ "Investment property"),
    manufactured_home_secured_property_type = case_when(
      manufactured_home_secured_property_type == 1 ~ "Manufactured home and land",
      manufactured_home_secured_property_type == 2 ~ "Manufactured home and not land",
      manufactured_home_secured_property_type == 3 ~ "Not applicable",
      manufactured_home_secured_property_type == 1111 ~ "Exempt"),
    manufactured_home_land_property_interest = case_when(
      manufactured_home_land_property_interest == 1 ~ "Direct ownership",
      manufactured_home_land_property_interest == 2 ~ "Indirect ownership",
      manufactured_home_land_property_interest == 3 ~ "Paid leasehold",
      manufactured_home_land_property_interest == 4 ~ "Unpaid leasehold",
      manufactured_home_land_property_interest == 5 ~ "Not applicable",
      manufactured_home_land_property_interest == 1111 ~ "Exempt"),
    applicant_credit_score_type = case_when(
      applicant_credit_score_type == 1 ~ "Equifax Beacon 5.0",
      applicant_credit_score_type == 2 ~ "Experian Fair Isaac",
      applicant_credit_score_type == 3 ~ "FICO Risk Score Classic 04",
      applicant_credit_score_type == 4 ~ "FICO Risk Score Classic 98",
      applicant_credit_score_type == 5 ~ "VantageScore 2.0",
      applicant_credit_score_type == 6 ~ "VantageScore 3.0",
      applicant_credit_score_type == 7 ~ "More than one credit scoring model",
      applicant_credit_score_type == 8 ~ "Other credit scoring model",
      applicant_credit_score_type == 9 ~ "Not applicable",
      applicant_credit_score_type == 1111 ~ "Exempt"),
    co_applicant_credit_score_type = case_when(
      co_applicant_credit_score_type == 1 ~ "Equifax Beacon 5.0",
      co_applicant_credit_score_type == 2 ~ "Experian Fair Isaac",
      co_applicant_credit_score_type == 3 ~ "FICO Risk Score Classic 04",
      co_applicant_credit_score_type == 4 ~ "FICO Risk Score Classic 98",
      co_applicant_credit_score_type == 5 ~ "VantageScore 2.0",
      co_applicant_credit_score_type == 6 ~ "VantageScore 3.0",
      co_applicant_credit_score_type == 7 ~ "More than one credit scoring model",
      co_applicant_credit_score_type == 8 ~ "Other credit scoring model",
      co_applicant_credit_score_type == 9 ~ "Not applicable",
      co_applicant_credit_score_type == 1111 ~ "Exempt"),
    applicant_ethnicity_1 = case_when(
      applicant_ethnicity_1 == 1 ~ "Hispanic or Latino",
      applicant_ethnicity_1 == 11 ~ "Mexican",
      applicant_ethnicity_1 == 12 ~ "Puerto Rican",
      applicant_ethnicity_1 == 13 ~ "Cuban",
      applicant_ethnicity_1 == 14 ~ "Other Hispanic or Latino",
      applicant_ethnicity_1 == 2 ~ "Not Hispanic or Latino",
      applicant_ethnicity_1 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_ethnicity_1 == 4 ~ "Not applicable"),
    applicant_ethnicity_2 = case_when(
      applicant_ethnicity_2 == 1 ~ "Hispanic or Latino",
      applicant_ethnicity_2 == 11 ~ "Mexican",
      applicant_ethnicity_2 == 12 ~ "Puerto Rican",
      applicant_ethnicity_2 == 13 ~ "Cuban",
      applicant_ethnicity_2 == 14 ~ "Other Hispanic or Latino",
      applicant_ethnicity_2 == 2 ~ "Not Hispanic or Latino",
      applicant_ethnicity_2 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_ethnicity_2 == 4 ~ "Not applicable"),
    applicant_ethnicity_3 = case_when(
      applicant_ethnicity_3 == 1 ~ "Hispanic or Latino",
      applicant_ethnicity_3 == 11 ~ "Mexican",
      applicant_ethnicity_3 == 12 ~ "Puerto Rican",
      applicant_ethnicity_3 == 13 ~ "Cuban",
      applicant_ethnicity_3 == 14 ~ "Other Hispanic or Latino",
      applicant_ethnicity_3 == 2 ~ "Not Hispanic or Latino",
      applicant_ethnicity_3 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_ethnicity_3 == 4 ~ "Not applicable"),
    applicant_ethnicity_4 = case_when(
      applicant_ethnicity_4 == 1 ~ "Hispanic or Latino",
      applicant_ethnicity_4 == 11 ~ "Mexican",
      applicant_ethnicity_4 == 12 ~ "Puerto Rican",
      applicant_ethnicity_4 == 13 ~ "Cuban",
      applicant_ethnicity_4 == 14 ~ "Other Hispanic or Latino",
      applicant_ethnicity_4 == 2 ~ "Not Hispanic or Latino",
      applicant_ethnicity_4 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_ethnicity_4 == 4 ~ "Not applicable"),
    applicant_ethnicity_5 = case_when(
      applicant_ethnicity_5 == 1 ~ "Hispanic or Latino",
      applicant_ethnicity_5 == 11 ~ "Mexican",
      applicant_ethnicity_5 == 12 ~ "Puerto Rican",
      applicant_ethnicity_5 == 13 ~ "Cuban",
      applicant_ethnicity_5 == 14 ~ "Other Hispanic or Latino",
      applicant_ethnicity_5 == 2 ~ "Not Hispanic or Latino",
      applicant_ethnicity_5 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_ethnicity_5 == 4 ~ "Not applicable"),
    co_applicant_ethnicity_1 = case_when(
      co_applicant_ethnicity_1 == 1 ~ "Hispanic or Latino",
      co_applicant_ethnicity_1 == 11 ~ "Mexican",
      co_applicant_ethnicity_1 == 12 ~ "Puerto Rican",
      co_applicant_ethnicity_1 == 13 ~ "Cuban",
      co_applicant_ethnicity_1 == 14 ~ "Other Hispanic or Latino",
      co_applicant_ethnicity_1 == 2 ~ "Not Hispanic or Latino",
      co_applicant_ethnicity_1 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_ethnicity_1 == 4 ~ "Not applicable",
      co_applicant_ethnicity_1 == 5 ~ "No co-applicant"),
    co_applicant_ethnicity_2 = case_when(
      co_applicant_ethnicity_2 == 1 ~ "Hispanic or Latino",
      co_applicant_ethnicity_2 == 11 ~ "Mexican",
      co_applicant_ethnicity_2 == 12 ~ "Puerto Rican",
      co_applicant_ethnicity_2 == 13 ~ "Cuban",
      co_applicant_ethnicity_2 == 14 ~ "Other Hispanic or Latino",
      co_applicant_ethnicity_2 == 2 ~ "Not Hispanic or Latino",
      co_applicant_ethnicity_2 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_ethnicity_2 == 4 ~ "Not applicable",
      co_applicant_ethnicity_2 == 5 ~ "No co-applicant"),
    co_applicant_ethnicity_3 = case_when(
      co_applicant_ethnicity_3 == 1 ~ "Hispanic or Latino",
      co_applicant_ethnicity_3 == 11 ~ "Mexican",
      co_applicant_ethnicity_3 == 12 ~ "Puerto Rican",
      co_applicant_ethnicity_3 == 13 ~ "Cuban",
      co_applicant_ethnicity_3 == 14 ~ "Other Hispanic or Latino",
      co_applicant_ethnicity_3 == 2 ~ "Not Hispanic or Latino",
      co_applicant_ethnicity_3 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_ethnicity_3 == 4 ~ "Not applicable",
      co_applicant_ethnicity_3 == 5 ~ "No co-applicant"),
    co_applicant_ethnicity_4 = case_when(
      co_applicant_ethnicity_4 == 1 ~ "Hispanic or Latino",
      co_applicant_ethnicity_4 == 11 ~ "Mexican",
      co_applicant_ethnicity_4 == 12 ~ "Puerto Rican",
      co_applicant_ethnicity_4 == 13 ~ "Cuban",
      co_applicant_ethnicity_4 == 14 ~ "Other Hispanic or Latino",
      co_applicant_ethnicity_4 == 2 ~ "Not Hispanic or Latino",
      co_applicant_ethnicity_4 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_ethnicity_4 == 4 ~ "Not applicable",
      co_applicant_ethnicity_4 == 5 ~ "No co-applicant"),
    co_applicant_ethnicity_5 = case_when(
      co_applicant_ethnicity_5 == 1 ~ "Hispanic or Latino",
      co_applicant_ethnicity_5 == 11 ~ "Mexican",
      co_applicant_ethnicity_5 == 12 ~ "Puerto Rican",
      co_applicant_ethnicity_5 == 13 ~ "Cuban",
      co_applicant_ethnicity_5 == 14 ~ "Other Hispanic or Latino",
      co_applicant_ethnicity_5 == 2 ~ "Not Hispanic or Latino",
      co_applicant_ethnicity_5 == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_ethnicity_5 == 4 ~ "Not applicable",
      co_applicant_ethnicity_5 == 5 ~ "No co-applicant"),
    applicant_ethnicity_observed = case_when(
      applicant_ethnicity_observed == 1 ~ "Collected on the basis of visual observation or surname",
      applicant_ethnicity_observed == 2 ~ "Not collected on the basis of visual observation or surname",
      applicant_ethnicity_observed == 3 ~ "Not applicable"),
    co_applicant_ethnicity_observed = case_when(
      co_applicant_ethnicity_observed == 1 ~ "Collected on the basis of visual observation or surname",
      co_applicant_ethnicity_observed == 2 ~ "Not collected on the basis of visual observation or surname",
      co_applicant_ethnicity_observed == 3 ~ "Not applicable",
      co_applicant_ethnicity_observed == 4 ~ "No co-applicant"),
    applicant_race_1 = case_when(
      applicant_race_1 == 1 ~ "American Indian or Alaska Native",
      applicant_race_1 == 2 ~ "Asian",
      applicant_race_1 == 21 ~ "Asian Indian",
      applicant_race_1 == 22 ~ "Chinese",
      applicant_race_1 == 23 ~ "Filipino",
      applicant_race_1 == 24 ~ "Japanese",
      applicant_race_1 == 25 ~ "Korean",
      applicant_race_1 == 26 ~ "Vietnamese",
      applicant_race_1 == 27 ~ "Other Asian",
      applicant_race_1 == 3 ~ "Black or African American",
      applicant_race_1 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      applicant_race_1 == 41 ~ "Native Hawaiian",
      applicant_race_1 == 42 ~ "Guamanian or Chamorro",
      applicant_race_1 == 43 ~ "Samoan",
      applicant_race_1 == 44 ~ "Other Pacific Islander",
      applicant_race_1 == 5 ~ "White",
      applicant_race_1 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_race_1 == 7 ~ "Not applicable"),
    applicant_race_2 = case_when(
      applicant_race_2 == 1 ~ "American Indian or Alaska Native",
      applicant_race_2 == 2 ~ "Asian",
      applicant_race_2 == 21 ~ "Asian Indian",
      applicant_race_2 == 22 ~ "Chinese",
      applicant_race_2 == 23 ~ "Filipino",
      applicant_race_2 == 24 ~ "Japanese",
      applicant_race_2 == 25 ~ "Korean",
      applicant_race_2 == 26 ~ "Vietnamese",
      applicant_race_2 == 27 ~ "Other Asian",
      applicant_race_2 == 3 ~ "Black or African American",
      applicant_race_2 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      applicant_race_2 == 41 ~ "Native Hawaiian",
      applicant_race_2 == 42 ~ "Guamanian or Chamorro",
      applicant_race_2 == 43 ~ "Samoan",
      applicant_race_2 == 44 ~ "Other Pacific Islander",
      applicant_race_2 == 5 ~ "White",
      applicant_race_2 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_race_2 == 7 ~ "Not applicable"),
    applicant_race_3 = case_when(
      applicant_race_3 == 1 ~ "American Indian or Alaska Native",
      applicant_race_3 == 2 ~ "Asian",
      applicant_race_3 == 21 ~ "Asian Indian",
      applicant_race_3 == 22 ~ "Chinese",
      applicant_race_3 == 23 ~ "Filipino",
      applicant_race_3 == 24 ~ "Japanese",
      applicant_race_3 == 25 ~ "Korean",
      applicant_race_3 == 26 ~ "Vietnamese",
      applicant_race_3 == 27 ~ "Other Asian",
      applicant_race_3 == 3 ~ "Black or African American",
      applicant_race_3 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      applicant_race_3 == 41 ~ "Native Hawaiian",
      applicant_race_3 == 42 ~ "Guamanian or Chamorro",
      applicant_race_3 == 43 ~ "Samoan",
      applicant_race_3 == 44 ~ "Other Pacific Islander",
      applicant_race_3 == 5 ~ "White",
      applicant_race_3 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_race_3 == 7 ~ "Not applicable"),
    applicant_race_4 = case_when(
      applicant_race_4 == 1 ~ "American Indian or Alaska Native",
      applicant_race_4 == 2 ~ "Asian",
      applicant_race_4 == 21 ~ "Asian Indian",
      applicant_race_4 == 22 ~ "Chinese",
      applicant_race_4 == 23 ~ "Filipino",
      applicant_race_4 == 24 ~ "Japanese",
      applicant_race_4 == 25 ~ "Korean",
      applicant_race_4 == 26 ~ "Vietnamese",
      applicant_race_4 == 27 ~ "Other Asian",
      applicant_race_4 == 3 ~ "Black or African American",
      applicant_race_4 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      applicant_race_4 == 41 ~ "Native Hawaiian",
      applicant_race_4 == 42 ~ "Guamanian or Chamorro",
      applicant_race_4 == 43 ~ "Samoan",
      applicant_race_4 == 44 ~ "Other Pacific Islander",
      applicant_race_4 == 5 ~ "White",
      applicant_race_4 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_race_4 == 7 ~ "Not applicable"),
    applicant_race_5 = case_when(
      applicant_race_5 == 1 ~ "American Indian or Alaska Native",
      applicant_race_5 == 2 ~ "Asian",
      applicant_race_5 == 21 ~ "Asian Indian",
      applicant_race_5 == 22 ~ "Chinese",
      applicant_race_5 == 23 ~ "Filipino",
      applicant_race_5 == 24 ~ "Japanese",
      applicant_race_5 == 25 ~ "Korean",
      applicant_race_5 == 26 ~ "Vietnamese",
      applicant_race_5 == 27 ~ "Other Asian",
      applicant_race_5 == 3 ~ "Black or African American",
      applicant_race_5 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      applicant_race_5 == 41 ~ "Native Hawaiian",
      applicant_race_5 == 42 ~ "Guamanian or Chamorro",
      applicant_race_5 == 43 ~ "Samoan",
      applicant_race_5 == 44 ~ "Other Pacific Islander",
      applicant_race_5 == 5 ~ "White",
      applicant_race_5 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_race_5 == 7 ~ "Not applicable"),
    co_applicant_race_1 = case_when(
      co_applicant_race_1 == 1 ~ "American Indian or Alaska Native",
      co_applicant_race_1 == 2 ~ "Asian",
      co_applicant_race_1 == 21 ~ "Asian Indian",
      co_applicant_race_1 == 22 ~ "Chinese",
      co_applicant_race_1 == 23 ~ "Filipino",
      co_applicant_race_1 == 24 ~ "Japanese",
      co_applicant_race_1 == 25 ~ "Korean",
      co_applicant_race_1 == 26 ~ "Vietnamese",
      co_applicant_race_1 == 27 ~ "Other Asian",
      co_applicant_race_1 == 3 ~ "Black or African American",
      co_applicant_race_1 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      co_applicant_race_1 == 41 ~ "Native Hawaiian",
      co_applicant_race_1 == 42 ~ "Guamanian or Chamorro",
      co_applicant_race_1 == 43 ~ "Samoan",
      co_applicant_race_1 == 44 ~ "Other Pacific Islander",
      co_applicant_race_1 == 5 ~ "White",
      co_applicant_race_1 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_race_1 == 7 ~ "Not applicable",
      co_applicant_race_1 == 8 ~ "No co-applicant"),
    co_applicant_race_2 = case_when(
      co_applicant_race_2 == 1 ~ "American Indian or Alaska Native",
      co_applicant_race_2 == 2 ~ "Asian",
      co_applicant_race_2 == 21 ~ "Asian Indian",
      co_applicant_race_2 == 22 ~ "Chinese",
      co_applicant_race_2 == 23 ~ "Filipino",
      co_applicant_race_2 == 24 ~ "Japanese",
      co_applicant_race_2 == 25 ~ "Korean",
      co_applicant_race_2 == 26 ~ "Vietnamese",
      co_applicant_race_2 == 27 ~ "Other Asian",
      co_applicant_race_2 == 3 ~ "Black or African American",
      co_applicant_race_2 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      co_applicant_race_2 == 41 ~ "Native Hawaiian",
      co_applicant_race_2 == 42 ~ "Guamanian or Chamorro",
      co_applicant_race_2 == 43 ~ "Samoan",
      co_applicant_race_2 == 44 ~ "Other Pacific Islander",
      co_applicant_race_2 == 5 ~ "White",
      co_applicant_race_2 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_race_2 == 7 ~ "Not applicable",
      co_applicant_race_2 == 8 ~ "No co-applicant"),
    co_applicant_race_3 = case_when(
      co_applicant_race_3 == 1 ~ "American Indian or Alaska Native",
      co_applicant_race_3 == 2 ~ "Asian",
      co_applicant_race_3 == 21 ~ "Asian Indian",
      co_applicant_race_3 == 22 ~ "Chinese",
      co_applicant_race_3 == 23 ~ "Filipino",
      co_applicant_race_3 == 24 ~ "Japanese",
      co_applicant_race_3 == 25 ~ "Korean",
      co_applicant_race_3 == 26 ~ "Vietnamese",
      co_applicant_race_3 == 27 ~ "Other Asian",
      co_applicant_race_3 == 3 ~ "Black or African American",
      co_applicant_race_3 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      co_applicant_race_3 == 41 ~ "Native Hawaiian",
      co_applicant_race_3 == 42 ~ "Guamanian or Chamorro",
      co_applicant_race_3 == 43 ~ "Samoan",
      co_applicant_race_3 == 44 ~ "Other Pacific Islander",
      co_applicant_race_3 == 5 ~ "White",
      co_applicant_race_3 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_race_3 == 7 ~ "Not applicable",
      co_applicant_race_3 == 8 ~ "No co-applicant"),
    co_applicant_race_4 = case_when(
      co_applicant_race_4 == 1 ~ "American Indian or Alaska Native",
      co_applicant_race_4 == 2 ~ "Asian",
      co_applicant_race_4 == 21 ~ "Asian Indian",
      co_applicant_race_4 == 22 ~ "Chinese",
      co_applicant_race_4 == 23 ~ "Filipino",
      co_applicant_race_4 == 24 ~ "Japanese",
      co_applicant_race_4 == 25 ~ "Korean",
      co_applicant_race_4 == 26 ~ "Vietnamese",
      co_applicant_race_4 == 27 ~ "Other Asian",
      co_applicant_race_4 == 3 ~ "Black or African American",
      co_applicant_race_4 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      co_applicant_race_4 == 41 ~ "Native Hawaiian",
      co_applicant_race_4 == 42 ~ "Guamanian or Chamorro",
      co_applicant_race_4 == 43 ~ "Samoan",
      co_applicant_race_4 == 44 ~ "Other Pacific Islander",
      co_applicant_race_4 == 5 ~ "White",
      co_applicant_race_4 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_race_4 == 7 ~ "Not applicable",
      co_applicant_race_4 == 8 ~ "No co-applicant"),
    co_applicant_race_5 = case_when(
      co_applicant_race_5 == 1 ~ "American Indian or Alaska Native",
      co_applicant_race_5 == 2 ~ "Asian",
      co_applicant_race_5 == 21 ~ "Asian Indian",
      co_applicant_race_5 == 22 ~ "Chinese",
      co_applicant_race_5 == 23 ~ "Filipino",
      co_applicant_race_5 == 24 ~ "Japanese",
      co_applicant_race_5 == 25 ~ "Korean",
      co_applicant_race_5 == 26 ~ "Vietnamese",
      co_applicant_race_5 == 27 ~ "Other Asian",
      co_applicant_race_5 == 3 ~ "Black or African American",
      co_applicant_race_5 == 4 ~ "Native Hawaiian or Other Pacific Islander",
      co_applicant_race_5 == 41 ~ "Native Hawaiian",
      co_applicant_race_5 == 42 ~ "Guamanian or Chamorro",
      co_applicant_race_5 == 43 ~ "Samoan",
      co_applicant_race_5 == 44 ~ "Other Pacific Islander",
      co_applicant_race_5 == 5 ~ "White",
      co_applicant_race_5 == 6 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_race_5 == 7 ~ "Not applicable",
      co_applicant_race_5 == 8 ~ "No co-applicant"),
    applicant_race_observed = case_when(
      applicant_race_observed == 1 ~ "Collected on the basis of visual observation or surname",
      applicant_race_observed == 2 ~ "Not collected on the basis of visual observation or surname",
      applicant_race_observed == 3 ~ "Not applicable"),
    co_applicant_race_observed = case_when(
      co_applicant_race_observed == 1 ~ "Collected on the basis of visual observation or surname",
      co_applicant_race_observed == 2 ~ "Not collected on the basis of visual observation or surname",
      co_applicant_race_observed == 3 ~ "Not applicable",
      co_applicant_race_observed == 4 ~ "No co-applicant"),
    applicant_sex = case_when(
      applicant_sex == 1 ~ "Male",
      applicant_sex == 2 ~ "Female",
      applicant_sex == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      applicant_sex == 4 ~ "Not applicable",
      applicant_sex == 6 ~ "Applicant selected both male and female"),
    co_applicant_sex = case_when(
      co_applicant_sex == 1 ~ "Male",
      co_applicant_sex == 2 ~ "Female",
      co_applicant_sex == 3 ~ "Information not provided by applicant in mail, internet, or telephone application",
      co_applicant_sex == 4 ~ "Not applicable",
      co_applicant_sex == 5 ~ "No co-applicant",
      co_applicant_sex == 6 ~ "Applicant selected both male and female"),
    applicant_sex_observed = case_when(
      applicant_sex_observed == 1 ~ "Collected on the basis of visual observation or surname",
      applicant_sex_observed == 2 ~ "Not collected on the basis of visual observation or surname",
      applicant_sex_observed == 3 ~ "Not applicable"),
    co_applicant_sex_observed = case_when(
      co_applicant_sex_observed == 1 ~ "Collected on the basis of visual observation or surname",
      co_applicant_sex_observed == 2 ~ "Not collected on the basis of visual observation or surname",
      co_applicant_sex_observed == 3 ~ "Not applicable",
      co_applicant_sex_observed == 4 ~ "No co-applicant"),
    submission_of_application = case_when(
      submission_of_application == 1 ~ "Submitted directly to your institution",
      submission_of_application == 2 ~ "Not submitted directly to your institution",
      submission_of_application == 3 ~ "Not applicable",
      submission_of_application == 1111 ~ "Exempt"),
    initially_payable_to_institution = case_when(
      initially_payable_to_institution == 1 ~ "Initially payable to your institution",
      initially_payable_to_institution == 2 ~ "Not initially payable to your institution",
      initially_payable_to_institution == 3 ~ "Not applicable",
      initially_payable_to_institution == 1111 ~ "Exempt"),
    aus_1 = case_when(
      aus_1 == 1 ~ "Desktop Underwriter (DU)",
      aus_1 == 2 ~ "Loan Prospector (LP) or Loan Product Advisor",
      aus_1 == 3 ~ "Technology Open to Approved Lenders (TOTAL) Scorecard",
      aus_1 == 4 ~ "Guaranteed Underwriting System (GUS)",
      aus_1 == 5 ~ "Other",
      aus_1 == 6 ~ "Not applicable",
      aus_1 == 7 ~ "Internal Proprietary System",
      aus_1 == 1111 ~ "Exempt"),
    aus_2 = case_when(
      aus_2 == 1 ~ "Desktop Underwriter (DU)",
      aus_2 == 2 ~ "Loan Prospector (LP) or Loan Product Advisor",
      aus_2 == 3 ~ "Technology Open to Approved Lenders (TOTAL) Scorecard",
      aus_2 == 4 ~ "Guaranteed Underwriting System (GUS)",
      aus_2 == 5 ~ "Other",
      aus_2 == 7 ~ "Internal Proprietary System"),
    aus_3 = case_when(
      aus_3 == 1 ~ "Desktop Underwriter (DU)",
      aus_3 == 2 ~ "Loan Prospector (LP) or Loan Product Advisor",
      aus_3 == 3 ~ "Technology Open to Approved Lenders (TOTAL) Scorecard",
      aus_3 == 4 ~ "Guaranteed Underwriting System (GUS)",
      aus_3 == 5 ~ "Other",
      aus_3 == 7 ~ "Internal Proprietary System"),
    aus_4 = case_when(
      aus_4 == 1 ~ "Desktop Underwriter (DU)",
      aus_4 == 2 ~ "Loan Prospector (LP) or Loan Product Advisor",
      aus_4 == 3 ~ "Technology Open to Approved Lenders (TOTAL) Scorecard",
      aus_4 == 4 ~ "Guaranteed Underwriting System (GUS)",
      aus_4 == 5 ~ "Other",
      aus_4 == 7 ~ "Internal Proprietary System"),
    aus_5 = case_when(
      aus_5 == 1 ~ "Desktop Underwriter (DU)",
      aus_5 == 2 ~ "Loan Prospector (LP) or Loan Product Advisor",
      aus_5 == 3 ~ "Technology Open to Approved Lenders (TOTAL) Scorecard",
      aus_5 == 4 ~ "Guaranteed Underwriting System (GUS)",
      aus_5 == 5 ~ "Other",
      aus_5 == 7 ~ "Internal Proprietary System"),
    denial_reason_1 = case_when(
      denial_reason_1 == 1 ~ "Debt-to-income ratio",
      denial_reason_1 == 2 ~ "Employment history",
      denial_reason_1 == 3 ~ "Credit history",
      denial_reason_1 == 4 ~ "Collateral",
      denial_reason_1 == 5 ~ "Insufficient cash (downpayment, closing costs)",
      denial_reason_1 == 6 ~ "Unverifiable information",
      denial_reason_1 == 7 ~ "Credit application incomplete",
      denial_reason_1 == 8 ~ "Mortgage insurance denied",
      denial_reason_1 == 9 ~ "Other",
      denial_reason_1 == 10 ~ "Not applicable"),
    denial_reason_2 = case_when(
      denial_reason_2 == 1 ~ "Debt-to-income ratio",
      denial_reason_2 == 2 ~ "Employment history",
      denial_reason_2 == 3 ~ "Credit history",
      denial_reason_2 == 4 ~ "Collateral",
      denial_reason_2 == 5 ~ "Insufficient cash (downpayment, closing costs)",
      denial_reason_2 == 6 ~ "Unverifiable information",
      denial_reason_2 == 7 ~ "Credit application incomplete",
      denial_reason_2 == 8 ~ "Mortgage insurance denied",
      denial_reason_2 == 9 ~ "Other",
      denial_reason_2 == 10 ~ "Not applicable"),
    denial_reason_3 = case_when(
      denial_reason_3 == 1 ~ "Debt-to-income ratio",
      denial_reason_3 == 2 ~ "Employment history",
      denial_reason_3 == 3 ~ "Credit history",
      denial_reason_3 == 4 ~ "Collateral",
      denial_reason_3 == 5 ~ "Insufficient cash (downpayment, closing costs)",
      denial_reason_3 == 6 ~ "Unverifiable information",
      denial_reason_3 == 7 ~ "Credit application incomplete",
      denial_reason_3 == 8 ~ "Mortgage insurance denied",
      denial_reason_3 == 9 ~ "Other",
      denial_reason_3 == 10 ~ "Not applicable"),
    denial_reason_4 = case_when(
      denial_reason_4 == 1 ~ "Debt-to-income ratio",
      denial_reason_4 == 2 ~ "Employment history",
      denial_reason_4 == 3 ~ "Credit history",
      denial_reason_4 == 4 ~ "Collateral",
      denial_reason_4 == 5 ~ "Insufficient cash (downpayment, closing costs)",
      denial_reason_4 == 6 ~ "Unverifiable information",
      denial_reason_4 == 7 ~ "Credit application incomplete",
      denial_reason_4 == 8 ~ "Mortgage insurance denied",
      denial_reason_4 == 9 ~ "Other",
      denial_reason_4 == 10 ~ "Not applicable")
    ) 
  
hmda_chicago_geo <- hmda_chicago |> left_join(geo, by = c("census_tract" = "GEOID"))

st_write(st_as_sf(hmda_chicago_geo), "data/hmda_chic_2018.geojson")

