---
title: "Day One: Introductions"
subtitle: "SDS 189: Data and Social Justice"
author: |
  Lindsay Poirier<br/>
  <span style = 'font-size: 70%;'>
  [Statistical & Data Sciences](http://www.smith.edu/sds), Smith College<br/>
  </span>
date: |
  Fall 2023<br/>
  `r sds::img_logo(width = 64)`
format: 
  revealjs:
    scrollable: true
    df-print: paged
    theme: [default]
    incremental: true
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
editor: source
execute:
  echo: true
  messages: false
  warnings: false
---

# You are being granted one wish: for access to any dataset that a private company or the government maintains. Which dataset would you choose and why?

---

## Who is the professor? Why is an anthropologist teaching data science?

- Please call me Lindsay (preferred), Professor Poirier, or Dr. Poirier
- Previously Assistant Professor of Science and Technology Studies at UC Davis
- Lab Manager at [BetaNYC](https://beta.nyc/)
- M.S./Ph.D. in Science and Technology Studies from Rensselaer Polytechnic Institute
- B.S. in Information Technology and Web Science from Rensselaer Polytechnic Institute
- Dancing, crafting, cooking, re-watching the same TV series over and over again.
- I have a *very* spunky dog Madison.

---

# How is this class strctured?

---


## Exercise: Imaginary Scenario

:::: {.columns}

::: {.column width="50%"}

> You just completed your first semester at Smith College and are home for a break. You run into an old peer from high school who proceeds to tell you that they don't believe women's colleges should exist because it excludes the male viewpoint and discriminates against men who wish to attend the school. 

:::

::: {.column width="50%"}

- With your neighbor, discuss what data you could present to respond to this individual.
- What presumptions are made in the individual's statement?
- Why would the data you present offer a compelling response?
  
:::
:::

---


## Syllabus Review

- Policies
- Grading Contract
- Course Website
- Perusall
- Slack

---

## Reading Tuesday

- Be sure to leave three substantive comments. 



